[project]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
description = "Redstart: A Lightweight Reusable Booster"
name = "redstart"
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]
version = "1.0.0"

[tasks]
dev = "marimo edit"
clean = "rm -rf __marimo__ && rm *.mp4"

[dependencies]
python = ">=3.13.1,<3.14"
sdl2 = ">=2.30.10,<3"
numpy = ">=2.2.3,<3"
scipy = ">=1.15.1,<2"
matplotlib = ">=3.10.0,<4"
jupyterlab = ">=4.3.5,<5"
autograd = ">=1.7.0,<2"
sympy = ">=1.13.3,<2"
tqdm = ">=4.67.1,<5"
marimo = ">=0.13.6,<0.14"
